### ISSUE TITLE
error: the path "packaging/k8s/manifests/" does not exist

### ISSUE THREAD

**Issue by zerotn3** [ameydev/gke-kubectl-action#3]
![image](https://user-images.githubusercontent.com/19245852/77779318-ea78ca00-7084-11ea-9707-6cf9d64231e2.png)
Im using package to practice but have issue. Please help me review

Thank you

**Comment by ameydev** [comment]
Hey @zerotn3 the path `packaging/k8s/manifests` is just an example. You have to set it to your k8s manifest file present in your repo. Or a directory where multiple manifest (yaml) files are present. 
Please replace its value with the relative path of k8s manifest present in your repo.
Thanks
